version: 2
jobs:
  test:
    docker:
      - image: holochain/holonix:latest

    steps:
      - checkout
      
      - run:
          name: Run all tests
          command: nix-shell https://holochain.love --run 'cd skeptic && cargo test --all'
  build-api:
    docker:
      - image: holochain/holonix:latest

    steps:
      - checkout
      
      - run:
          name: Build api docs 
          command: nix-shell https://holochain.love --run './build_docs.sh 0.0.29-alpha2 0.0.29-alpha2'
      - persist_to_workspace:
                root: build/
                paths:
                  - api
                  - guide
                  - site
  build-mkdocs:
    docker:
      - image: squidfunk/mkdocs-material

    steps:
      - checkout
      - attach_workspace:
          at: build/ 
      - run:
          name: Build mkdocs 
          command: mkdocs build -d build/site,
      - persist_to_workspace:
                root: build/
                paths:
                  - api
                  - guide
                  - site
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: build/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.1.1
            git config user.email "ci-build@klukas.net"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "08:d9:fc:72:f9:a4:ab:26:5f:32:29:2e:15:f1:85:ee"
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Updates" -d build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-api:
          filters:
            branches:
              only: master 
      - build-mkdocs:
          requires:
            - build-api
          filters:
            branches:
              only: master 
      - test:
          filters:
            branches:
              only: master 
      - docs-deploy:
          requires:
            - build-api
            - build-mkdocs
          filters:
            branches:
              only: master 
