version: 2
jobs:
  generate_and_test:
    docker:
      - image: holochain/holonix:latest

    steps:
      - checkout
      - run:
          name: Get single_source 
          command: nix-shell https://holochain.love --run 'git clone https://github.com/freesig/single_source.git && cd single_source && cargo build --release && cp target/release/single_source ../single_source'
      - run:
          name: Run all tests
          command: nix-shell https://holochain.love --run './build_test_cc.sh hello_holo && ./build_and_test.sh hello_test && ./build_and_test.sh hello_gui && ./build_and_test.sh hello_me && ./build_and_test.sh hello_world && ./build_and_test.sh simple_micro_blog'
      - run:
          name: Push generated file
          command: git add docs && git commit -m "[skip ci] pushing generated files" && git push origin develop

  build-api:
    docker:
      - image: holochain/holonix:latest

    steps:
      - checkout
      - restore_cache:
          key: -V1-build/api/0.0.29-alpha2
      - restore_cache:
          key: -V1-build/guide/0.0.29-alpha2
      - run:
          name: Build api docs 
          command: nix-shell https://holochain.love --run './build_docs.sh 0.0.29-alpha2 0.0.29-alpha2'
      - save_cache:
          key: -V1-build/api/0.0.29-alpha2
          paths:
            - "build/api/0.0.29-alpha2"
      - save_cache:
          key: -V1-build/guide/0.0.29-alpha2
          paths:
            - "build/guide/0.0.29-alpha2"
      - persist_to_workspace:
          root: build
          paths:
            - api/*
            - guide/*
            - site/*
  build-mkdocs:
    docker:
      - image: squidfunk/mkdocs-material

    steps:
      - checkout
      - attach_workspace:
          at: build
      - run:
          name: Build mkdocs 
          command: mkdocs build -d build/site
      - run:
          name: debug2
          command: ls .
      - run:
          name: debug3
          command: ls build/
      - run:
          name: debug4
          command: pwd 
      - run:
          name: debug
          command: ls build/site
      - persist_to_workspace:
          root: build
          paths:
            - api/*
            - guide/*
            - site/*
  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: build/
      - run:
          name: Install and configure dependencies
          command: |
            npm install -g --silent gh-pages@2.1.1
      - add_ssh_keys:
          fingerprints:
            - "08:d9:fc:72:f9:a4:ab:26:5f:32:29:2e:15:f1:85:ee"
      - run:
          name: debug
          command: ls build/site
      - run:
          name: Deploy docs to gh-pages branch
          command: gh-pages --message "[skip ci] Updates" -d build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build-api:
          filters:
            branches:
              only: master 
      - build-mkdocs:
          requires:
            - build-api
          filters:
            branches:
              only: master 
      - generate_and_test:
          filters:
            branches:
              only: 
                - master
                - develop
      - docs-deploy:
          requires:
            - build-api
            - build-mkdocs
          filters:
            branches:
              only: master 
