version: 2
jobs:
  build:
    docker:
      - image: holochain/holonix:latest

    steps:
      - checkout
      
      - run:
          name: Run all tests
          command: nix-shell https://holochain.love --run 'cd skeptic && cargo test --all'
